name: Test Deployment

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'
    
    - name: Build
      run: ./gradlew clean build --info --stacktrace
      timeout-minutes: 10

    - name: Upload mod files
      uses: actions/upload-artifact@v4
      with:
        name: mod-files
        path: build/libs/*.jar
        if-no-files-found: error

    - name: Publish to Modrinth
      run: ./gradlew modrinth --stacktrace
      env:
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
        MODRINTH_VERSION_TYPE: 'alpha'
        MODRINTH_CHANGELOG_TEXT: 'Available at https://github.com/litetex-oss/mcm-cape-provider/blob/dev/CHANGELOG.md<br/><i>Please not that this is a SNAPSHOT which might be unstable</i>'
      timeout-minutes: 10
    
    - name: Publish to OSSRH
      run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository --stacktrace
      env:
        MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        S01_OSS_SONATYPE_MAVEN_USERNAME: ${{ secrets.S01_OSS_SONATYPE_MAVEN_USERNAME }}
        S01_OSS_SONATYPE_MAVEN_TOKEN: ${{ secrets.S01_OSS_SONATYPE_MAVEN_TOKEN }}
      timeout-minutes: 30
